apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serverdeployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.serverdeployment.image }}:{{ .Values.serverdeployment.tag }}"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: docker-credentials
