apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: http-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  rules:
    - http:
      paths:
        - path: /test
          pathType: Prefix
          backend:
            service:
              name: test
              port:
                number: 80
