apiVersion: v1
kind: Service
metadata:
  name: helm-server-load-balancer
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Values.appName }}
  type: LoadBalancer
